### ISSUE TITLE
TODO: write a benchmark program

### ISSUE THREAD

**Issue by kamalmarhubi** [asomers/tokio-file#1]
Very curious about how this performs vs a threadpool + [`futures::sync::oneshot`](https://docs.rs/futures/0.1.10/futures/sync/oneshot/index.html).

**Comment by asomers** [comment]
Good question.  Probably better, since it doesn't create any new OS threads.

**Comment by kamalmarhubi** [comment]
I remember reading this on the topic a while back, which is why I was curious: http://blog.libtorrent.org/2012/10/asynchronous-disk-io/

**Comment by asomers** [comment]
Interesting read.  I didn't know about the alignment restrictions for libaio.  That's going to cause problems for tokio-file.

**Comment by asomers** [comment]
I added a simple microbenchmark that does a single 4KB read using tokio-file.  For comparison, I added another microbenchmark that does the same 4KB read using `futures::sync::oneshot`in a new thread.  On my system, POSIX AIO usually wins by about 4-5x.  For example:
```
running 2 tests
test bench_aio_read      ... bench:       7,069 ns/iter (+/- 210)
test bench_threaded_read ... bench:      33,967 ns/iter (+/- 287
```
