### ISSUE TITLE
Request: Implement AsyncRead and AsyncWrite from tokio-io

### ISSUE THREAD

**Issue by mehcode** [asomers/tokio-file#3]
https://docs.rs/tokio-io/0.1.3/tokio_io/trait.AsyncWrite.html
https://docs.rs/tokio-io/0.1.3/tokio_io/trait.AsyncRead.html

Not sure if you've seen these yet as they're fairly new. The `tokio-io` crate provides useful utilities on top of those traits like https://docs.rs/tokio-io/0.1.3/tokio_io/io/fn.write_all.html .

**Comment by asomers** [comment]
I'm not sure what it would even mean. Tokio-io looks very socket-centric.  Those traits operate at the file pointer, for example, whereas tokio-file's methods all operate at a given offset.  And write_all doesn't make much sense either, because tokio-file's write method never returns a short write.

**Comment by mehcode** [comment]
It'd at least make it much simpler to pipe reads from an asynchronous thing that does chunked reads like an http response to a file from tokio-file using `tokio_io::copy`.

**Comment by asomers** [comment]
But again, `tokio_io::copy` expects to write to the end of a file, whereas `tokio_file::File::write_at` writes at a specified offset within the middle of the file.  So what would you expect `tokio_file::File::write_buf` to do?  Are you asking for me to basically implement these traits in parallel with tokio-file's existing methods?  I don't think they would do what you want.  You can't simply treat a file as a socket and make nonblocking writes and reads.  That will work, but you won't get nonblocking behavior, because I'm pretty sure that writing to an ordinary file will never return `EAGAIN`, even if disk I/O is necessary to complete the write.

**Comment by mehcode** [comment]
Okay. I'll have to experiment and get back to you. Sorry but I know nothing about async File IO and why it's weird and different than socket IO. 

My gut tells me we should do this because io is io but you're probably right that it doesn't make sense.

I haven't sat down and played with the library set so I'll do that and get back to you. I want to look at Linux support as well and what it means.

**Comment by griff** [comment]
@mehcode I was confused as well until I realised that `AsyncRead`/`AsyncWrite` are not asynchronous but only non-blocking. It should be possible to make a type that implements `AsyncRead`/`AsyncWrite` and uses `tokio_file::File` but I am not sure that it is worth the extra buffer and memory copying.

@asomers Wouldn't it make sense to add types/functions instead for common operations? Things like copy all from `AsyncRead` to `tokio_file::File` and copy all from `tokio_file::File` to `AsyncWrite`?

**Comment by asomers** [comment]
@griff @mehcode have you two looked at tokio-file-unix ?  If you want a file to work just like a socket, that's probably what you should be using.  It might not be truly asynchronous, but it provides sequential access, including the `std::io::AsyncRead` and `std::io::AsyncWrite` traits.  Tokio-file is really for applications that require random access.

**Comment by griff** [comment]
@asomers I tried that first but it is not for regular files. For regular files it simply works synchronously.

I have decided to simply use a `CpuPool` and `pread` for now since I already use a CpuPool for `symlink_metadata` and other file system API's.

**Comment by mehcode** [comment]
Looking back at this I realize this library is not what I want, sorry for the noise @asomers. I'd love a `std::fs` facade that pushed everything into `futures-cpupool`.

**Comment by asomers** [comment]
Ok, I'm going to close this issue as a misunderstanding.
